// screenit-frontend/medewerkerportaal/src/app/shared/toast/component/toast.component.ts
/*-
 * ========================LICENSE_START=================================
 * medewerkerportaal
 * %%
 * Copyright (C) 2012 - 2025 Facilitaire Samenwerking Bevolkingsonderzoek
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */
import { Component, inject } from '@angular/core'

import { ClrAlertModule } from '@clr/angular'
import { animate, style, transition, trigger } from '@angular/animations'
import { ToastService } from '@shared/toast/service/toast.service'
import { takeUntilDestroyed } from '@angular/core/rxjs-interop'
import { debounce, filter, timer } from 'rxjs'
import { SanitizePipe } from '@shared/pipes/sanitize/sanitize.pipe'
import { Toast } from '@shared/types/toast'

@Component({
  selector: 'app-toast',
  imports: [ClrAlertModule, SanitizePipe],
  templateUrl: './toast.component.html',
  styleUrls: ['./toast.component.scss'],
  animations: [
    trigger('fadeSlideInOut', [
      transition(':enter', [style({ opacity: 0, transform: 'translateY(10px)' }), animate('200ms', style({ opacity: 1, transform: 'translateY(0)' }))]),
      transition(':leave', [animate('200ms', style({ opacity: 0, transform: 'translateY(10px)' }))]),
    ]),
  ],
})
export class ToastComponent {
  toasts: Toast[] = []
  private toastService: ToastService = inject(ToastService)
  private updateDelay = 300

  constructor() {
    this.toastService.showToast$
      .pipe(
        takeUntilDestroyed(),
        filter((toast) => !this.hasToast(toast)),
        debounce(() => timer(this.updateDelay)),
      )
      .subscribe((toast: Toast) => {
        this.toasts.push(toast)

        if (toast.autoClose) {
          setTimeout(() => {
            this.closeToast(toast.id)
          }, toast.autoClose + this.updateDelay)
        }
      })

    this.toastService.hideToast$
      .pipe(
        takeUntilDestroyed(),
        debounce(() => timer(this.updateDelay)),
      )
      .subscribe((message: string) => {
        const index = this.toasts.findIndex((toast) => toast.message === message)
        if (index !== -1) {
          this.toasts.splice(index, 1)
        }
      })

    this.toastService.clearToasts$.pipe(takeUntilDestroyed()).subscribe(() => {
      this.toasts = []
    })
  }

  closeToast(id: number) {
    const index = this.toasts.findIndex((toast) => toast.id === id)
    if (index !== -1) {
      this.toasts.splice(index, 1)
    }
  }

  private hasToast(toast: Toast): boolean {
    return this.toasts.find((_toast) => _toast.message === toast.message) != undefined
  }
}

<!--
  ========================LICENSE_START=================================
  medewerkerportaal
  %%
  Copyright (C) 2012 - 2026 Facilitaire Samenwerking Bevolkingsonderzoek
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  =========================LICENSE_END==================================
  -->
@for (toast of toasts; track toast; let i = $index) {
  <clr-alert
    @fadeSlideInOut
    [clrAlertAppLevel]="false"
    [clrAlertClosable]="!toast.disableClose"
    [clrAlertType]="toast.type"
    [attr.data-testid]="'toast_' + i"
    (clrAlertClosedChange)="closeToast(toast.id)"
  >
    <clr-alert-item>
      @if (Array.isArray(toast.message)) {
        <div class="alert-text">
          <ul>
            @for (messagePart of toast.message; track messagePart) {
              <li [innerHTML]="messagePart | sanitize"></li>
            }
          </ul>
        </div>
      } @else {
        <div class="alert-text" [innerHTML]="toast.message | sanitize"></div>
      }
    </clr-alert-item>
  </clr-alert>
}

// screenit-huisartsenportaal/frontend/src/components/overlay/toast/ToastComponent.tsx
/*-
 * ========================LICENSE_START=================================
 * screenit-huisartsenportaal-frontend
 * %%
 * Copyright (C) 2012 - 2026 Facilitaire Samenwerking Bevolkingsonderzoek
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */
import classNames from "classnames"
import styles from "./ToastComponent.module.scss"
import {Toast, ToastType} from "../../../state/datatypes/Toast"
import {useDispatch} from "react-redux"
import {useCallback, useEffect, useState} from "react"
import {createActionHideToast} from "../../../state/ToastsState"

export interface ToastComponentProps {
	toast: Toast;
}

const ToastComponent = (props: ToastComponentProps) => {
	const dispatch = useDispatch()
	const [isDismissed, setIsDismissed] = useState<boolean>(false)

	const dismiss = useCallback(() => {
		if (!isDismissed) {
			setIsDismissed(true)
			setTimeout(() => {
				dispatch(createActionHideToast(props.toast.id))
			}, 1000)
		}
	}, [dispatch, isDismissed, setIsDismissed, props.toast.id])

	useEffect(() => {
		setTimeout(() => {
			dismiss()
		}, 5000)
	}, [dispatch, isDismissed, dismiss])

	return <div className={classNames(styles.style, getToastStyle(props.toast.type), isDismissed && styles.dismiss, "p-4", "rounded-3", "fw-bold", "my-3")} onClick={dismiss}>
		{props.toast.message}
	</div>
}

function getToastStyle(type: ToastType) {
	switch (type) {
		case ToastType.SUCCESS:
			return styles.success
		case ToastType.INFO:
			return styles.info
		case ToastType.WARN:
			return styles.warn
		case ToastType.ERROR:
			return styles.error
	}
}

export default ToastComponent
