// screenit-frontend/medewerkerportaal/src/app/app.component.ts
/*-
 * ========================LICENSE_START=================================
 * medewerkerportaal
 * %%
 * Copyright (C) 2012 - 2026 Facilitaire Samenwerking Bevolkingsonderzoek
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */
import { AfterViewInit, Component, ElementRef, inject } from '@angular/core'
import { SessionTimeoutService } from '@shared/session-timeout/service/session-timeout.service'
import { Router, RouterOutlet } from '@angular/router'

@Component({
  selector: 'app-root',
  template: ` <router-outlet></router-outlet>`,
  imports: [RouterOutlet],
})
export class AppComponent implements AfterViewInit {
  private elementRef: ElementRef = inject(ElementRef)
  private sessionTimeoutService: SessionTimeoutService = inject(SessionTimeoutService)
  private readonly router = inject(Router)

  get componentName(): string | null {
    return this.elementRef.nativeElement.getAttribute('data-component')
  }

  ngAfterViewInit() {
    this.sessionTimeoutService.startSessionTimer()
    let route = '/'
    switch (this.componentName) {
      case 'colon-rooster':
        route = '/darmkanker/rooster'
        break
      case 'feestdagen-beheer':
        route = '/darmkanker/feestdagen-beheer'
        break
      case 'weekend-werkdag-beheer':
        route = '/darmkanker/weekend-werkdag-beheer'
        break
      case 'dense2-uitwisseling':
        route = '/borstkanker/dense2-uitwisseling'
        break
      case 'extra-beveiligde-omgeving-keuze-herstellen':
        route = '/extra-beveiligde-omgeving/keuze-herstellen'
        break
      case 'extra-beveiligde-omgeving-client-zoeken':
        route = '/extra-beveiligde-omgeving/client-zoeken'
        break
      case 'mamma-visitatie-overzicht':
        route = '/borstkanker/visitatie'
        break
      case 'mamma-fotobespreking-onderzoeken':
        route = '/borstkanker/fotobespreking/onderzoeken'
        break
      case 'handleidingen-overzicht':
        route = '/handleidingen'
        break
      case 'client-zoeken':
        route = '/client/zoeken'
        break
    }
    this.router.events.subscribe((event) => {
      console.log(event)
    })

    this.router.navigateByUrl(route)
  }
}

<!--
  ========================LICENSE_START=================================
  medewerkerportaal
  %%
  Copyright (C) 2012 - 2025 Facilitaire Samenwerking Bevolkingsonderzoek
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  =========================LICENSE_END==================================
  -->
<ng-container appComponentLoader></ng-container>
<app-toast/>

// screenit-clientportaal/frontend/src/App.tsx
/*-
 * ========================LICENSE_START=================================
 * screenit-clientportaal-frontend
 * %%
 * Copyright (C) 2012 - 2026 Facilitaire Samenwerking Bevolkingsonderzoek
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */
import "bootstrap/dist/css/bootstrap.min.css"
import "./scss/style.scss"
import styles from "./App.module.scss"
import {Container} from "react-bootstrap"
import {AppRoutes} from "./routes"
import HeaderComponent from "./components/header/HeaderComponent"
import FooterComponent from "./components/footer/FooterComponent"
import ActiveToastsComponent from "./components/toast/ActiveToastsComponent"
import {useGotoPageTop, useHideAllToasts, useRefreshBvoDossier, useRefreshClient, useRefreshEnvironmentInfo} from "./utils/Hooks"
import LoadingSpinnerOverlay from "./components/loading/LoadingSpinnerOverlay"
import UnsupportedBrowserBanner from "./components/banner/unsupportedbrowser/UnsupportedBrowserBanner"

const App = () => {
	useRefreshEnvironmentInfo()
	useRefreshClient()
	useRefreshBvoDossier()
	useHideAllToasts()
	useGotoPageTop()

	return (
		<div className={styles.app}>
			<Container className={styles.appBody} fluid>
				<ActiveToastsComponent/>
				<LoadingSpinnerOverlay/>
				<HeaderComponent/>
				<Container fluid className={styles.appContent}>
					<UnsupportedBrowserBanner/>
					<AppRoutes/>
				</Container>
			</Container>
			<FooterComponent/>
		</div>
	)
}

export default App
